### ISSUE TITLE
Handling of integers

### ISSUE THREAD

**Issue by maelh** [neslib/Neslib.MultiPrecision#1]
Great library, thanks for making it available for Delphi!

I was wondering how integers are handled. Extended/float80 can represent 64 bit integers without rounding, which makes it and ideal type to hold floats as well as integers.

Can DoubleDouble do this as well? Are integers guaranteed to be preserved if the operations don't involve fractions?
Is there a possibility to do precise division by an integer and truncating the fractional part?

**Comment by neslib** [comment]
I don't know how integers are handled internally. You would have to run some tests to find out.
BTW: Extended/float only works in 32-bit mode on Intel CPUs, so I shouldn't rely on this if you need to branch out to other platforms or 64-bit code in the future. (On those platforms, Extended is identical to Double).

The library doesn't natively support dividing by integers: the integer will get converted to a Double first (with potential loss of precision for very large integers). If a DoubleDouble can hold all integer values you care about, then you should create a DoubleDouble with the integer value and then divide by that DoubleDouble. You can than truncate the result.

Hope this helps.

**Comment by maelh** [comment]
Thanks. Regarding Extended/float80, I am aware it is not supported on every platform. But you can add it back into Win64 using assembly and a similar approach you used in your project :)
