### ISSUE TITLE
Let's keep improving the parser...

### ISSUE THREAD

**Issue by Andreas113** [neslib/Neslib.MultiPrecision#6]
Hi Erik, 
Sorry to pester and harass you again, but I suffer from the nasty disease called perfectionism. My motto and guiding principle in programming is as follows: **Make the software intelligent, because the user is stupid anyway.**
So: let's keep improving the parser, if you like...
```
Function: Division
Example:

Y/X:
----
X            =   1
Y            = - 0
MPA_Float    = 0 ---> Correct
QuadDouble   = NAN
DoubleDouble = NAN

Y/X:
----
X            =   1
Y            = -2
MPA_Float    = -2 ---> Correct
QuadDouble   = NAN
DoubleDouble = NAN

Y/X:
----
X            = + 1
Y            = -2
MPA_Float    = -2 ---> Correct
QuadDouble   = NAN
DoubleDouble = NAN

Y/X:
----
X            =   1
Y            = - 2
MPA_Float    = -2 ---> Correct
QuadDouble   = NAN
DoubleDouble = NAN

Y/X:
----
X            =   1
Y            = - 2
MPA_Float    = -2 ---> Correct
QuadDouble   = NAN
DoubleDouble = NAN
```
The input strings are not parsed correctly. But the above cases can be solved very easily by **trimming** the inputs.
A bit more complex, but solvable is the following case:
```

Y/X:
----
X            = 1E - 1
Y            = - 2
MPA_Float    = -20 ---> Correct
QuadDouble   = -2.00000000000000000000000000000000000000000000000000000000000000
DoubleDouble = -2.0000000000000000000000000000000
```
Thanks
Andreas

**Comment by Andreas113** [comment]
All such "stupid" inputs containing spaces can be easily solved by removing all spaces and making the program more secure. The following routine is very suitable for this purpose:

```
{
  Deletes all occurrences of sub-String Needle from String HayStack AND returns
  the resulting String. HayStack is returned unchanged If it does NOT contain
  Needle. The search is Case sensitive.
}
Function DelAllStr(CONST Needle, Haystack: String): String;
// http://delphidabbler.com/url/csdb.
Var
  StartIdx: Integer;
Begin
  Result:= Haystack;
  StartIdx:= SysUtils.AnsiPos(Needle, Result);
  While StartIdx > 0 Do
  Begin
    Delete(Result, StartIdx, Length(Needle));
    StartIdx:= SysUtils.AnsiPos(Needle, Result);
  End;
End;
```
A call like this solves all these problems:
```
CONST
  Space = ‘ ’;
. . .
S:= DelAllStr(Space, S);
. . .
```
Andreas

**Comment by neslib** [comment]
We are entering a bit of a grey area here. Usually, whitespace is used to separate multiple values. In that case it shouldn't be ignored. Also, entering whitespace in "normal" floating-point literals is not allowed in Delphi.

I will look into this this weekend if I have some time. In general, I want to follow the same conventions as the Delphi RTL. So if the standard StrToFloat function does not accept whitespace, then neither should the DoubleDouble/QuadDouble version.

One way to make stupid users less stupid is to not accept stupid inputs😉

**Comment by Andreas113** [comment]
OK Erik, agree with you. But then such an input as follows should not be accepted at all, because thereby an apparent result - namely a wrong one - comes out:
```
Y/X:
----
X            = 1E - 1
Y            = - 2
MPA_Float    = -20 ---> Correct
QuadDouble   = -2.00000000000000000000000000000000000000000000000000000000000000
DoubleDouble = -2.0000000000000000000000000000000
```
Thanks
Andreas

**Comment by neslib** [comment]
I made some changes to make the parsing behave more like Delphi's `StrToFloat`:

- When using the implicit String operator (as in `X := '- 2'`), it will raise an EConvertError exception now when the input is invalid, so it will not create invalid output.
- Leading and trailing whitespace is accepted (as in `StrToFloat`).
- Other whitespace is regarded as a separator and stops parsing at that point. So `X := '1 2'` is parsed successfully as `1`, but `X := '- 2`' results in an error because `'-'` by itself is not a valid number.

This will probably not account for all possible (parsing) errors, but it is more closely in line with what Delphi's `StrToFloat` does.

Let me know if there are any other cases where the behavior differs from the `StrToFloat` behavior.
